### ISSUE TITLE
Discussion: should we abstract clang-format and tslint?

### ISSUE THREAD

**Issue by JustinBeckwith** [google/ts-style#1]
Letting users control the typescript and tsconfig.json is absolutely the right call.  For clang and tslint though...  I wonder out loud if we shouldn't entirely abstract them behind a custom purpose binary.  For example - today our npm scripts look like this:

```json
  "scripts": {
    "build": "npm run compile",
    "clean": "rm -rf ./build/",
    "compile": "tsc -p . --rootDir . --outDir build/",
    "format": "clang-format -i -style=\"{Language: JavaScript, BasedOnStyle: Google, ColumnLimit: 80}\" src/*.ts test/*.ts",
    "lint": "tslint -c ../../.npm/_npx/30782/lib/node_modules/google-ts-style/tslint.json -p . -t codeFrame --type-check"
  },
```

If we provided a special purpose non-configurable binary, it would look like this:

```json
"scripts": {
    "build": "npm run compile",
    "clean": "rm -rf ./build/",
    "compile": "tsc -p . --rootDir . --outDir build/",
    "format": "gts format src/*.ts test/*.ts",
    "lint": "gts lint"
},
```

I could also make the argument for `gts clean`, as I don't know if windows will support `rm -rf` that easily.  

It would reduce dependencies down as well:

```json
"devDependencies": {
    "google-ts-style": "latest",
    "typescript": "^2.4.1"
}
```

**Comment by ofrobots** [comment]
+1. See this [TODO](https://github.com/google/ts-style/blob/99f833fa743316d72c29e78c147aa9f63e9d1e8e/src/init.ts#L58) in the code:

```js
    // TODO(ofrobots): use a clang-format wrapper so that it can use the files,
    // include, and exclude sections from tsconfig.json.
    format:
        `clang-format -i -style="{Language: JavaScript, BasedOnStyle: Google,` +
        ` ColumnLimit: 80}" ${defaultSources}`,
```

Wanna write a PR? :wink:

**Comment by ofrobots** [comment]
The argument for `gts clean` is a good one too. As a pre-requisite we should move the `--outDir` and `--rootDir` options to tsconfig.json as well. This removes pretty much all configuration from the npm scripts (apart from `-p .` for compile).

**Comment by JustinBeckwith** [comment]
FYI - working on a PR for abstracting lint.

**Comment by JustinBeckwith** [comment]
Pretty sure the latest PR #15 actually finishes all of this off :)
