### ISSUE TITLE
Error in tsconfig.json after running `npx gts init`

### ISSUE THREAD

**Issue by doplumi** [google/ts-style#128]
`The specified path does not exist: '/users/dom/.npm/_npx/98679/lib/node_modules/gts/tsconfig-google.json'.`

**Comment by jinwoo** [comment]
I believe this was fixed by https://github.com/google/ts-style/pull/114. But we haven't released a new version yet.

@ofrobots Can we release a new version?

**Comment by doplumi** [comment]
@jinwoo great, plus I just noticed, it downloads Chromium for some reason? I've got puppeteer as a dependency, but what does gts wants to do with it?

**Comment by doplumi** [comment]
Also – going back on topic – it doesn't seem to install any `tslint.json`. Is that part of the same issue @jinwoo?

**Comment by jinwoo** [comment]
`gts` doesn't download Chromium by itself. What happens is `gts init` runs `npm install` after initializing the project and because your projects depends on puppeteer, `npm install` downloads Chromium.

**Comment by jinwoo** [comment]
`gts init` doesn't install `tslint.json` in your project's directory. It just uses the `tslint.json` file in the `gts` directory.

**Comment by jinwoo** [comment]
0.5.4 has been published. Please check with the new version. Thanks again for the bug report. Closing now.
