### ISSUE TITLE
Drop support for Node 4

### ISSUE THREAD

**Issue by ofrobots** [google/ts-style#135]
Opening issues for the 1.0 milestone. Node is going to go EOL by end of April, so let's drop support for it. This needs to happen in a semver major, so 1.0 is a good target.

* [ ] Update `engines.node` field in package.json.
* [ ] Change default target to ES2016. Node 6 has [almost everything](https://node.green) in ES2016. 
* [ ] Enable `--esModuleInterop` (already present in `next` branch).

**Comment by jinwoo** [comment]
Also maybe
- [ ] Enable `--esModuleInterop`

It is in the `next` branch.

**Comment by ofrobots** [comment]
Done via #146.
