### ISSUE TITLE
tsx support?

### ISSUE THREAD

**Issue by hvent90** [google/ts-style#156]
Hi all,

Thanks for writing such a wonderful package.

`npm run check` returns the following error if a `.tsx` file is present:
`Error parsing -style: Unsuitable`

**Update**: Changing `baseArgs` to `['style', 'file']` in `./node_modules/gts/build/src/format.js` (line 13) and moving `.clang-format` from `./node_modules/gts` to `./node_modules/gts/build/src` stopped the error from showing.

**Comment by ofrobots** [comment]
Thanks for reporting the problem @hvent90. It seems like the default config expects all files meant to be input for the TypeScript compiler will be `.ts` files and runs clang-format on them with the JavaScript style – resulting in the error reported above. We'll look into a fix.

**Comment by ofrobots** [comment]
Fixed via #259.
