### ISSUE TITLE
Is JSDoc required for TypeScript projects?

### ISSUE THREAD

**Issue by hvent90** [google/ts-style#168]
Hi all,

Apologies if this question is out of scope of this project.

I noticed that Google's Javascript Style Guide includes JSDoc requirements -- [JSDoc is used on all classes, fields, and functions](https://google.github.io/styleguide/jsguide.html#jsdoc). 

Is this requirement also true for TypeScript projects?

Cheers

**Comment by ofrobots** [comment]
I believe this has been answered so I am going to close this out. If there is still more issues to discuss, please add a comment, and I will reopen.
