### ISSUE TITLE
Print `clang-format` output

### ISSUE THREAD

**Issue by kjin** [google/ts-style#181]
In #60:

> A fix for this should be landed shortly (#62); all it does is add an error message if linting succeeds and formatting fails. I'm planning to add parsing `clang-format` XML output as a follow-up (PRs from your end would be more than welcome too). That being said, it's best to run `gts fix` to fix format issues anyway; I believe `clang-format` output is not necessarily meant to be human-interpretable.

When `clang-format` fails, all we do is print that there were formatting issues. `gts fix` fixes those issues, but it would still be nice to show the lines of code that need to be addressed.

**Comment by JustinBeckwith** [comment]
Playing devil's advocate here - why should we care?  I the fix is always "just run `gts fix`", I'm not sure what value showing the format error provides. What is the value of showing it?
