### ISSUE TITLE
Can I use Yarn other than NPM?

### ISSUE THREAD

**Issue by Artsiomxau** [google/ts-style#201]

**Comment by ofrobots** [comment]
Hi @Artsiomxau. You should be able to use this with yarn just fine. All of the operations and run scripts should work. For simplicity's sake we only include `npm` instructions in the README.

I am going to close this issue as 'answered'. Please add a comment if the answer doesn't sufficiently address your question.

**Comment by Artsiomxau** [comment]
@ofrobots  I understand that we did so for the simplicity of README. However, I think it is right to comment on the supporting packaging manager. I don't think this is a difficult problem. If there is any way you can help me improve README, please let me know.
