### ISSUE TITLE
discussion:  we have too many names 😂

### ISSUE THREAD

**Issue by JustinBeckwith** [google/ts-style#21]
![bikeshed time](http://whatshed.co.uk/wp-content/uploads/2015/05/7x3-Waltons-Tongue-and-Groove-Apex-Wooden-Bike-Shed-Overall-View.jpg)

In a perfect world, we would have the same name for:
* The repository name
* The npm module name
* The binary name used in `npm run`

Today all three of these are different for us :(   We have:
* `google/ts-style` for the GitHub name
* `google-ts-style` as the npm module name
* `gts` as the binary name

I think reducing this down into one name would make everything a lot easier to remember, and easier for new users figuring things out.  

So to make things more concrete...

![some suggestions](https://i.imgflip.com/1tmrnn.jpg)

Let me throw out a few ideas.  

1. We could rename the npm module to `gts` to keep it consistent with the binary.  Optionally, we could consider renaming the GitHub repo.  
2. We could pick a new name for all three, and try to move it all together.  Some ideas (all available on npm):
  - `typefix`
  - `@google/standardts`
  - `blueshed`
  - `Any others welcomed....

Thoughts?  Calling @ofrobots @MylesBorins @jmdobry ...

**Comment by ofrobots** [comment]
Some Observations:

* How frequently do we expect people to type in them module binary name? The expected workflow is only once: `npx google-ts-style init`. After than you just use your npm scripts. Perhaps we need to stop using the `gts` abbreviation and prefer `google-ts-style` as the binary name.
* A shorter name would indeed be nice.
* `gts` is probably not a good short name; `oh-my-zsh` has a default alias that would override the binary. However, if the users are never running `gts` unadorned (i.e. without `npx` or `$(npm bin)/`), perhaps this doesn't matter?
* `blueshed` is way too subtle.
* `@google/standardts` is descriptive, but equally as mouthful as `google-ts-style`.
* `typefix` would be a good name if this was just a linter + formatter. It is more.

Note that I am not a strongly opposed to any one of the above if people feel strongly for them.

Other ideas to throw out:
* `typegoo`
* `goots` – for completeness.
* `tsktsk` – may be hard to enunciate.

**Comment by JustinBeckwith** [comment]
All good points.  Given the isseus with `gts` and with `blueshed` being too subtle...  I vote we go back to `goots`.  Eh?

**Comment by ofrobots** [comment]
Fixed by #47.
