### ISSUE TITLE
"clang-format" produces incorrectly-whitespaced Zone#import declaration in nodejs-dns

### ISSUE THREAD

**Issue by carnesen** [google/ts-style#214]
Of course there's some subjectivity in what constitutes "proper" whitespace, but I think we can all agree that [this line in nodejs-dns](https://github.com/googleapis/nodejs-dns/blob/9742e9e15994f9b98c4ca8f0ad65eed4423e94ff/src/zone.ts#L1016) is incorrect: 
```
import(localPath: string, callback: CreateChangeCallback) {fs.readFile(localPath, 'utf-8', (err, file) => {
```
Whereas the other method declarations for this class start at column 3 (i.e. a single, two-space indent), this `import` method starts at column 1 as if it were a top-level statement in the module. Furthermore, though ["ColumnLimit" is set to 80 in that project](https://github.com/googleapis/nodejs-dns/blob/127c10e4e4aec1c476d8d2f956f5cf953ea3dfdf/.clang-format#L3), this line is an unacceptably-long 107 columns.

Note: I'm filing this mostly to help make my case for a switch to Prettier in googleapis/google-cloud-node#2842 . I'll be adding a comment there soon that references this issue. If we switch to tslint + prettier (via tslint-plugin-prettier and tslint-config-prettier), this issue will be fixed "for free".

**Comment by ofrobots** [comment]
Switched to `prettier` via #259.
