### ISSUE TITLE
"clang-format" changes behavior of ServiceObject constructor in nodejs-common

### ISSUE THREAD

**Issue by carnesen** [google/ts-style#215]
As a developer, I expect that my reformatter won't change the runtime behavior of my code. Unfortunately under some conditions `clang-format` injects non-cosmetic whitespace. See [this section of code](https://github.com/googleapis/nodejs-common/blob/509c3abc6df499b1f6d824f947cdf0457f69153e/src/service-object.ts#L180) in nodejs-common:
```TypeScript
            return (
                // All ServiceObjects need `request`.
                // clang-format off
                !/^request/.test(methodName) &&
                // clang-format on
                // The ServiceObject didn't redefine the method.
                this[methodName] === ServiceObject.prototype[methodName] &&
                // This method isn't wanted.
                !config.methods![methodName]);
```
If I remove the off/on comments,`clang-format` produces the following output:

```TypeScript
            return (
                // All ServiceObjects need `request`.
                ! / ^request /.test(methodName) &&
                // The ServiceObject didn't redefine the method.
                this[methodName] === ServiceObject.prototype[methodName] &&
                // This method isn't wanted.
                !config.methods![methodName]);
```

The spaces inserted into the regex change it's runtime behavior.

Note: I'm filing this mostly to help make my case for a switch to Prettier in googleapis/google-cloud-node#2842 . I'll be adding a comment there soon that references this issue. If we switch to tslint + prettier (via tslint-plugin-prettier and tslint-config-prettier), this issue will be fixed "for free".

**Comment by ofrobots** [comment]
Fixed by #259
