### ISSUE TITLE
"clang-format" has trouble with union types

### ISSUE THREAD

**Issue by 43081j** [google/ts-style#247]
```ts
export const foo = {
  test(val: string): boolean | null {
    return !!val;
  }
};

// same for the long version

export const foo = {
  test: function(val: string): boolean | null {
    return !!val;
  }
};
```

Either of these result in:

```ts
export const foo = {
  test(val: string): boolean |
      null {
        return !!val;
      }
};
```

😞

**Comment by 43081j** [comment]
Also, decorators are placed on a single line:

```ts
@foo({a: foo, b: foo, c: foo}) public prop: Object;
```

Is this expected?

**Comment by ofrobots** [comment]
I have opened a bug against clang-format for this. I'll close this out as this is not actionable locally other than waiting for upstream to fix, or switching to `prettier` as per #225.

**Comment by 43081j** [comment]
Can you provide a link to the bug so we can follow it?

**Comment by ofrobots** [comment]
I opened an internal bug, unfortunately I don't have a public link to it. If there are updates on the bug I will post them here.
