### ISSUE TITLE
Misalignment in variable declaration

### ISSUE THREAD

**Issue by Maxim-Mazurok** [google/ts-style#274]
Example source:
```ts
const somewhatLongName1: number = 2 * 20000000000000, somewhatLongName2: number = 2 * 20000000000000;
```
after running `gts fix`:
```ts
const somewhatLongName1: number = 2 * 20000000000000,
                         somewhatLongName2: number = 2 * 20000000000000;
```
expected result:
```ts
const somewhatLongName1: number = 2 * 20000000000000,
  somewhatLongName2: number = 2 * 20000000000000;
```
or:
```ts
const somewhatLongName1: number = 2 * 20000000000000,
      somewhatLongName2: number = 2 * 20000000000000;
```

-----
Versions:
gts: 0.9.0
node: v9.11.2

-----
`.clang-format`:
```
Language:        JavaScript
BasedOnStyle:    Google
ColumnLimit:     80
```
`tslint.json`:
```
{
  "extends": "gts/tslint.json",
  "rules": {
    "no-any": false
  }
}
```

**Comment by JustinBeckwith** [comment]
Greetings!  In the upcoming 1.x (available now on master...), we're using `prettier` instead of `clang-format` for formatting changes.  Would you mind giving that a shot and seeing if it works for you?

**Comment by Maxim-Mazurok** [comment]
Hi, thanks for the prompt response!
Master branch did the trick, it produced:
```ts
const somewhatLongName1: number = 2 * 20000000000000,
  somewhatLongName2: number = 2 * 20000000000000;
```
Now I can configure my WebStorm to format code the same way, problem solved, thanks again!

**Comment by ofrobots** [comment]
Closing as this is fixed on `master`.
