### ISSUE TITLE
Error when running build for the first time

### ISSUE THREAD

**Issue by matthewloring** [google/ts-style#34]
$ npm run build

> my-module@1.0.0 build /Documents/my-module
> npm run compile

> my-module@1.0.0 compile /Documents/pallas
> tsc -p .

error TS18001: A path in an 'extends' option must be relative or rooted, but 'node_modules/google-ts-style/tsconfig-google.json' is not.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-module@1.0.0 compile: `tsc -p .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-module@1.0.0 compile script.

**Comment by ofrobots** [comment]
What version of g-t-s?

**Comment by matthewloring** [comment]
0.1.2

**Comment by matthewloring** [comment]
I was able to work around by changing the generated `tsconfig.json` from 
```
"extends": "node_modules/google-ts-style/tsconfig-google.json"
```
 to 
```
"extends": "./node_modules/google-ts-style/tsconfig-google.json"
```

**Comment by ofrobots** [comment]
Thanks, Should be easy to fix here: https://github.com/google/ts-style/blob/master/src/init.ts#L149. Wanna submit a PR?

**Comment by matthewloring** [comment]
Yup

**Comment by ofrobots** [comment]
I believe this is fixed now. Reopen if you're still seeing issues. The module has been renamed to `gts` now.
