### ISSUE TITLE
`gts check` can fail with no output

### ISSUE THREAD

**Issue by kjin** [google/ts-style#60]

**Comment by KamranAsif** [comment]
This is blocking me as well. Any updates on this?

**Comment by kjin** [comment]
A fix for this should be landed shortly (#62); all it does is add an error message if linting succeeds and formatting fails. I'm planning to add parsing `clang-format` XML output as a follow-up (PRs from your end would be more than welcome too). That being said, it's best to run `gts fix` to fix format issues anyway; I believe `clang-format` output is not necessarily meant to be human-interpretable.
