### ISSUE TITLE
`gts clean` doesn't follow tsconfig.json dependency chain

### ISSUE THREAD

**Issue by kjin** [google/ts-style#64]
If my `tsconfig.json` extends `tsconfig.other.json` with no additional parameters, `gts clean` will fail because it can't read `build` in `tsconfig.json`.

It should try to detect the extension chain and find the `build` field in `tsconfig.other.json`. Any other command that relies on a field in `tsconfig.json` might have the same issue.

**Comment by ofrobots** [comment]
This wasn't an intended use-case (I was imagining a single hop). I am concerned that we may have to do these dependency walks in quite a few cases. This will need an abstraction to ensure that this gets handled transparently everywhere. If a PR is available, I think we should consider this feature request.
