### ISSUE TITLE
New version converts `any` to `{}` too aggressively

### ISSUE THREAD

**Issue by jinwoo** [google/ts-style#80]
For code like this:
```typescript
import {EventEmitter} from 'events';

interface MyData {
  foo: string;
}

class Foo extends EventEmitter {
  on(event: 'mydata', listener: (data: MyData) => void): this;
  on(event: string, listener: (...args: any[]) => void): this {
    return super.on(event, listener);
  }
}
```
, `gts fix` converts `...args: any[]` to `...args: {}[]`, which makes the specialized `on()` method (for 'mydata') not compatible with the implementation and makes the build fail. I think this must be left as `any[]` because the super class (`EventEmitter`)'s type is `any[]`.

That also brings another problem where the linter complains about `{}[]`, saying that
> Array type using 'T[]' is forbidden for non-simple types. Use'Array<T>' instead.

Which forces me to write `Array<{}>`, which is harder to read than `{}[]` or `any[]`. It surprises me that it says `{}` is of a non-simple type.

**Comment by jinwoo** [comment]
I'm guessing that's caused by the addition of the `"no-any": true` rule at https://github.com/google/ts-style/commit/dae4e41618bf7bc5858cd19bf29341620a03bf8e#diff-ace19bd0c04529e685320269e3c05de9R28

**Comment by JustinBeckwith** [comment]
As I go through the google-auth-library and try to make it work with gts - I can confirm that this rule is cruel and usual.

**Comment by jinwoo** [comment]
I'm closing this after an internal discussion.

The consensus seems to be "Disallow `any`. Use `tslint:disable-next-line:no-any` when it's legit".

```typescript
// tslint:disable-next-line:no-any The parent `EventEmitter` uses ...args: any[]
on(event: string, listener: (...args: any[]) => void): this {
  ...
```

**Comment by calebegg** [comment]
I think this should be re-opened. It's a bad idea to apply fixes for no-any automatically, as it will almost always break code. Other lint checks probably are unsafe to apply automatically in certain circumstances, but this one is especially bad.

See discussion here: https://github.com/palantir/tslint/issues/2491, especially last comment.

**Comment by ofrobots** [comment]
Agree with @calebegg. The `no-any` rule should not have a fixer.

I propose that we implement our own `no-any-google` rule that jettisons the fixer and use that instead. Or convince upstream to do it.

**Comment by JustinBeckwith** [comment]
I'm +1 on this approach - having the lint rule is ok, breaking all of my code when I run `fix` isn't.

**Comment by JustinBeckwith** [comment]
I'm pretty sure this is already fixed.  Not sure if it happened here or somewhere upstream 😆 Feel free to re-open if it's still an issue.
