### ISSUE TITLE
Scope of this project & style guide debates

### ISSUE THREAD

**Issue by ofrobots** [google/ts-style#85]
Consider #80. Even though the issue is closed there are some points the disposition and approach to that issue raise:

* The aim of this project (`gts`) seems to be to enable the Google style guide for anyone (Google, non-Google) who wants to use it.
* However, it is not the right venue to debate the style guide itself. We are basically mirroring what Google uses internally and cannot (should not) editorialize the style itself.
* This means that this repo isn't the best venue to debate the style guide.
* The style guide document itself isn't public (yet). This makes it hard for users to understand the context and rationale behind the style rules.

The question becomes, how do we deal with critiques of the style guide:

1. 'This is not the correct venue for debates on the style guide'. This is unfulfilling for external users.
1. Try to proxy concerns between internal and external venues. Somewhat better but still unfulfilling.
1. Over the longer term, make this repo host the externalized style guide & make this authoritative?

@JustinBeckwith @mprobst: Thoughts?

**Comment by JustinBeckwith** [comment]
Great discussion topic.  I'm already running into issues where I need to go digging into the private TypeScript style guide to figure out why rules are the way they are.  

I think we should have the TypeScript rules published here:
https://github.com/google/styleguide

And have a public page similar to this:
https://google.github.io/styleguide/jsguide.html

In fullness of time - I think convergence is the only viable option.  One set of rules, internally and externally.  I think it's great to engage in conversations about the rules, with the understanding that at the end of the day we have the final call.

**Comment by mprobst** [comment]
Proxy to internal debates seems reasonable for the time being. We try to be
reasonable and responsive :-) though might fail occasionally.

I do agree it'd be nice to publish the style guide itself.

**Comment by ofrobots** [comment]
Hi @SystemDisc. Thanks for your comment. I'm glad that you are finding this stuff useful! 

We do hope to have the style guide available publicly at some point, but don't have a concrete timeline for it just yet. *nudges* @mprobst.

**Comment by ofrobots** [comment]
I'm going to close this issue as there isn't anything immediately actionable on this repo. We are hopeful that the style guide would be public at some point.
