### ISSUE TITLE
Running `npm install` after `npx gts init`

### ISSUE THREAD

**Issue by JustinBeckwith** [google/ts-style#90]
So I've done this a few times now.  I will run `npx gts init`, then immediately try doing a `npm run compile`.  This always fails with an error like this:

```
error TS5058: The specified path does not exist:
 '/users/beckwith/code/testy/node_modules/gts/tsconfig-google.json'.
```

Then I remember to run `npm install`, and everything is fine.  Is it possible to kick off an `npm install` after `npx gts init` modifies my `package.json`?

**Comment by ofrobots** [comment]
+1. Good idea. PRs welcome :).
