### ISSUE TITLE
Improve `check` performance on large code bases

### ISSUE THREAD

**Issue by JustinBeckwith** [google/ts-style#95]
Running `gts check` on the google-api-nodejs-client can take kind of a long time (minutes).  To improve performance, would it be possible to do some sort of incremental build, where we only run the tool on files that have changed?

**Comment by jinwoo** [comment]
Doesn't something like this work?
```shell
npm run check -- src/foo.ts src/bar.ts ...
```

**Comment by JustinBeckwith** [comment]
Not really.  I want to run `npm run check` after `npm test`, just like we set up with init.

**Comment by ofrobots** [comment]
In my experiments it was around 24 seconds, not minutes :p. Here's a profile that shows something interesting:

![image](https://user-images.githubusercontent.com/79017/33352418-a647e73c-d45d-11e7-81ff-73e5ffeb988f.png)

Why so much idle?

I think it would be better to fix this idle time issue before diving into keeping track of changed files between runs.

**Comment by JustinBeckwith** [comment]
I am guilty of exaggerating.  When you add up the many times I run tests, it hits minutes quick though 😂

**Comment by ofrobots** [comment]
Okay, so the 'idle' time is actually clang format. It seems that checking format takes longer than running lint, even though clang-format is implemented in C++.

**Comment by usergenic** [comment]
Is it a design choice to suppress the details of tslint and/or clang-format errors?
```
clang-format reported errors... run `gts fix` to address.
```
I feel like a default "show all the errors" behavior would be preferable with an option to suppress?

**Comment by ofrobots** [comment]
We have switched to `prettier` via #259 (on the `next` branch). If this is still an issue, it probably belongs on the `prettier` repo.

@usergenic the details of the formatting errors are now shown in detail.
